[package]
name = "reddb-io-toon-rpc-tcp"
version.workspace = true
description = "TOON-RPC TCP and Unix Socket transports"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
reddb-io-toon-rpc = { path = "../reddb-io-toon-rpc", version = "0.29.5" }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
serde_json = "1"

[dev-dependencies]
tokio-test = "0.4"
