import assert from 'node:assert/strict';
import { PassThrough } from 'node:stream';
import { test } from 'node:test';
import { Client, RpcError, Server } from '../dist/index.js';
import { StdioTransport } from '../dist/stdio.js';
import { serveStdio } from '../dist/serve.js';
// Generated by reddb-io-toon-rpc-gen from
// crates/reddb-io-toon-rpc-codegen/examples/calculator.toonrpc; run by Node's
// type stripping and type-checked by `pnpm test`.
import { CalculatorClient, registerCalculator } from './generated/calculator.ts';

function calculatorServer() {
  const server = new Server();
  registerCalculator(server, {
    add: (a, b) => a + b,
    divide(a, b) {
      if (b === 0) throw new RpcError(-32602, 'division by zero');
      return a / b;
    },
    norm: (v) => Math.hypot(v.x, v.y),
    stats: (values) => ({
      count: values.length,
      mean: values.length === 0 ? null : values.reduce((sum, value) => sum + value, 0) / values.length,
    }),
  });
  return server;
}

test('the generated client calls the generated server', async () => {
  const toServer = new PassThrough();
  const toClient = new PassThrough();
  serveStdio(calculatorServer(), { input: toServer, output: toClient });
  const client = new Client(new StdioTransport({ input: toClient, output: toServer }));
  const calculator = new CalculatorClient(client);

  assert.equal(await calculator.add(2, 3), 5);
  assert.equal(await calculator.norm({ x: 3, y: 4 }), 5);
  assert.deepEqual(await calculator.stats([1, 2, 6]), { count: 3, mean: 3 });
  assert.deepEqual(await calculator.stats([]), { count: 0, mean: null });
  await assert.rejects(calculator.divide(1, 0), (error) => error instanceof RpcError && error.code === -32602);

  // Positional params in declaration order work too; the wrong shape is refused.
  assert.equal(await client.call('add', [2, 3]), 5);
  await assert.rejects(client.call('add', [2]), (error) => error.code === -32602);
  await client.close();
  toServer.end();
});
