[package]
name = "reddb-io-toon-rpc-examples"
version = "0.29.0"
description = "TOON-RPC examples (calculator server/client)"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "calculator_server"
path = "src/calculator_server.rs"

[[bin]]
name = "calculator_client"
path = "src/calculator_client.rs"

[[bin]]
name = "calculator_stdio_server"
path = "src/calculator_stdio_server.rs"

[[bin]]
name = "calculator_stdio_client"
path = "src/calculator_stdio_client.rs"

[[bin]]
name = "multi_calculator_server"
path = "src/multi_calculator_server.rs"

[dependencies]
reddb-io-toon-rpc = { path = "../reddb-io-toon-rpc" }
reddb-io-toon-rpc-http = { path = "../reddb-io-toon-rpc-http" }
reddb-io-toon-rpc-tcp = { path = "../reddb-io-toon-rpc-tcp" }
tokio = { version = "1", features = ["full"] }
serde_json = "1"
async-trait = "0.1"
