//! Rust output: the types, a service trait, a function registering an
//! implementation on a `Dispatcher`, and a typed client. Meant to be its own
//! module file (it carries inner attributes). Requires `serde` (derive) and
//! `serde_json` next to `reddb-io-toon-rpc`.

use std::fmt::Write;

use crate::idl::{Field, Method, Service, Type};

pub fn generate(service: &Service) -> String {
    let mut out = String::new();
    let name = &service.name;
    let snake = snake_case(name);
    let _ = writeln!(
        out,
        "//! Generated by reddb-io-toon-rpc-gen from the {name} IDL (version {}). Do not edit.",
        service.version
    );
    out.push_str(concat!(
        "#![allow(dead_code, non_snake_case, clippy::too_many_arguments)]\n\n",
        "use std::sync::Arc;\n\n",
        "use reddb_io_toon_rpc::{Client, ClientError, Dispatcher, Params, RpcError, RpcResult};\n",
        "use serde::{Deserialize, Serialize};\n",
    ));

    for ty in &service.types {
        let _ = write!(
            out,
            "\n#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\npub struct {} {{\n",
            ty.name
        );
        for field in &ty.fields {
            let _ = writeln!(out, "    pub {}: {},", field.name, rust_type(&field.ty));
        }
        out.push_str("}\n");
    }

    let _ = write!(
        out,
        "\n/// The {name} service.\npub trait {name}: Send + Sync + 'static {{\n"
    );
    for method in &service.methods {
        let _ = writeln!(
            out,
            "    fn {}(&self{}) -> RpcResult<{}>;",
            method.name,
            params_list(&method.params),
            rust_type(&method.result)
        );
    }
    out.push_str("}\n");

    let _ = write!(
        out,
        "\n/// Register every {name} method on `dispatcher`, answered by `service`.\n\
         pub fn register_{snake}(dispatcher: &mut Dispatcher, service: Arc<dyn {name}>) {{\n"
    );
    for method in &service.methods {
        register_method(&mut out, &snake, method);
    }
    out.push_str("}\n");

    let _ = write!(
        out,
        "\n/// A typed {name} client over any `Client`.\n\
         #[derive(Clone)]\n\
         pub struct {name}Client {{\n    client: Client,\n}}\n\n\
         impl {name}Client {{\n    pub fn new(client: Client) -> Self {{\n        Self {{ client }}\n    }}\n"
    );
    for method in &service.methods {
        client_method(&mut out, method);
    }
    out.push_str("}\n");

    let _ = write!(
        out,
        "\n/// Read the params by name (an object) or by position (an array in\n\
         /// declaration order).\n\
         fn {snake}_params<T: serde::de::DeserializeOwned>(\n    params: Params,\n    names: &[&str],\n) -> Result<T, RpcError> {{\n\
         \x20   let object = match params {{\n\
         \x20       Params::ByName(object) => object,\n\
         \x20       Params::ByPosition(values) if values.len() == names.len() => {{\n\
         \x20           names.iter().map(|name| name.to_string()).zip(values).collect()\n\
         \x20       }}\n\
         \x20       Params::Absent if names.is_empty() => serde_json::Map::new(),\n\
         \x20       _ => {{\n\
         \x20           return Err(RpcError::InvalidParams(format!(\n\
         \x20               \"expected {{}} params\",\n\
         \x20               names.len()\n\
         \x20           )))\n\
         \x20       }}\n\
         \x20   }};\n\
         \x20   serde_json::from_value(serde_json::Value::Object(object))\n\
         \x20       .map_err(|error| RpcError::InvalidParams(error.to_string()))\n\
         }}\n"
    );
    out
}

fn register_method(out: &mut String, snake: &str, method: &Method) {
    let names = method
        .params
        .iter()
        .map(|field| format!("{:?}", field.name))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = write!(
        out,
        "    let service_for_{0} = service.clone();\n\
         \x20   dispatcher.register({0:?}, move |params, _id| {{\n\
         \x20       #[derive(Deserialize)]\n\
         \x20       #[serde(deny_unknown_fields)]\n\
         \x20       struct Args {{\n",
        method.name
    );
    for field in &method.params {
        let _ = writeln!(out, "            {}: {},", field.name, rust_type(&field.ty));
    }
    let arguments = method
        .params
        .iter()
        .map(|field| format!("args.{}", field.name))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = write!(
        out,
        "        }}\n\
         \x20       let args: Args = {snake}_params(params, &[{names}])?;\n\
         \x20       let result = service_for_{0}.{0}({arguments})?;\n\
         \x20       serde_json::to_value(result).map_err(|error| RpcError::InternalError(error.to_string()))\n\
         \x20   }});\n",
        method.name
    );
}

fn client_method(out: &mut String, method: &Method) {
    let _ = write!(
        out,
        "\n    pub async fn {}(&self{}) -> Result<{}, ClientError> {{\n\
         \x20       let mut params = serde_json::Map::new();\n",
        method.name,
        params_list(&method.params),
        rust_type(&method.result)
    );
    for field in &method.params {
        let _ = writeln!(
            out,
            "        params.insert({:?}.into(), serde_json::to_value({}).map_err(|error| ClientError::InvalidCall(error.to_string()))?);",
            field.name, field.name
        );
    }
    let _ = write!(
        out,
        "        let result = self.client.call({:?}, Params::ByName(params)).await?;\n\
         \x20       serde_json::from_value(result).map_err(|error| ClientError::Protocol(error.to_string()))\n\
         \x20   }}\n",
        method.name
    );
}

fn params_list(params: &[Field]) -> String {
    params
        .iter()
        .map(|field| format!(", {}: {}", field.name, rust_type(&field.ty)))
        .collect()
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Bool => "bool".into(),
        Type::I32 => "i32".into(),
        Type::I64 => "i64".into(),
        Type::U32 => "u32".into(),
        Type::U64 => "u64".into(),
        Type::F64 => "f64".into(),
        Type::String => "String".into(),
        Type::Json => "serde_json::Value".into(),
        Type::Null => "()".into(),
        Type::Named(name) => name.clone(),
        Type::List(inner) => format!("Vec<{}>", rust_type(inner)),
        Type::Optional(inner) => format!("Option<{}>", rust_type(inner)),
    }
}

/// `MathService` → `math_service`.
pub(crate) fn snake_case(name: &str) -> String {
    let mut out = String::new();
    for (index, c) in name.char_indices() {
        if c.is_ascii_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}
