//! TypeScript output: the types, a service interface, a function registering
//! an implementation on a `Server`, and a typed client. Plain TypeScript with
//! no parameter properties or enums, so it also runs under Node's type
//! stripping.

use std::fmt::Write;

use crate::idl::{Field, Method, Service, Type};

pub fn generate(service: &Service) -> String {
    let mut out = String::new();
    let name = &service.name;
    let camel = lower_first(name);
    let _ = writeln!(
        out,
        "// Generated by reddb-io-toon-rpc-gen from the {name} IDL (version {}). Do not edit.",
        service.version
    );
    out.push_str(concat!(
        "import { RpcError } from '@reddb-io/toon-rpc';\n",
        "import type { Client, CoreValue, Params, Server } from '@reddb-io/toon-rpc';\n",
    ));

    for ty in &service.types {
        let _ = write!(out, "\nexport interface {} {{\n", ty.name);
        for field in &ty.fields {
            let _ = writeln!(out, "  {}: {};", field.name, ts_type(&field.ty));
        }
        out.push_str("}\n");
    }

    let _ = write!(
        out,
        "\n/** The {name} service. */\nexport interface {name} {{\n"
    );
    for method in &service.methods {
        let result = ts_type(&method.result);
        let _ = writeln!(
            out,
            "  {}({}): {result} | Promise<{result}>;",
            method.name,
            params_list(&method.params)
        );
    }
    out.push_str("}\n");

    let _ = write!(
        out,
        "\n/** Register every {name} method on `server`, answered by `service`. */\n\
         export function register{name}(server: Server, service: {name}): void {{\n"
    );
    for method in &service.methods {
        register_method(&mut out, &camel, method);
    }
    out.push_str("}\n");

    let _ = write!(
        out,
        "\n/** A typed {name} client over any `Client`. */\n\
         export class {name}Client {{\n\
         \x20 private readonly client: Client;\n\n\
         \x20 constructor(client: Client) {{\n\
         \x20   this.client = client;\n\
         \x20 }}\n"
    );
    for method in &service.methods {
        client_method(&mut out, method);
    }
    out.push_str("}\n");

    let _ = write!(
        out,
        "\n/** Read the params by name (an object) or by position (an array in declaration order). */\n\
         function {camel}Params(params: Params | undefined, names: readonly string[]): unknown[] {{\n\
         \x20 if (Array.isArray(params)) {{\n\
         \x20   if (params.length === names.length) return params;\n\
         \x20 }} else if (params !== undefined) {{\n\
         \x20   const record = params as Record<string, unknown>;\n\
         \x20   if (names.every((name) => Object.hasOwn(record, name))) return names.map((name) => record[name]);\n\
         \x20 }} else if (names.length === 0) {{\n\
         \x20   return [];\n\
         \x20 }}\n\
         \x20 throw new RpcError(-32602, `expected params ${{names.join(', ')}}`);\n\
         }}\n"
    );
    out
}

fn register_method(out: &mut String, camel: &str, method: &Method) {
    let names = method
        .params
        .iter()
        .map(|field| format!("'{}'", field.name))
        .collect::<Vec<_>>()
        .join(", ");
    let bindings = method
        .params
        .iter()
        .map(|field| field.name.clone())
        .collect::<Vec<_>>()
        .join(", ");
    let arguments = method
        .params
        .iter()
        .map(|field| format!("{} as {}", field.name, ts_type(&field.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    let _ = writeln!(
        out,
        "  server.register('{}', async (params) => {{",
        method.name
    );
    if !method.params.is_empty() {
        let _ = writeln!(
            out,
            "    const [{bindings}] = {camel}Params(params, [{names}]);"
        );
    } else {
        let _ = writeln!(out, "    {camel}Params(params, []);");
    }
    let _ = write!(
        out,
        "    return (await service.{}({arguments})) as unknown as CoreValue;\n  }});\n",
        method.name
    );
}

fn client_method(out: &mut String, method: &Method) {
    let fields = method
        .params
        .iter()
        .map(|field| field.name.clone())
        .collect::<Vec<_>>()
        .join(", ");
    let result = ts_type(&method.result);
    let _ = write!(
        out,
        "\n  async {}({}): Promise<{result}> {{\n\
         \x20   const params = {{ {fields} }} as unknown as Params;\n\
         \x20   return (await this.client.call('{}', params)) as unknown as {result};\n\
         \x20 }}\n",
        method.name,
        params_list(&method.params),
        method.name
    );
}

fn params_list(params: &[Field]) -> String {
    params
        .iter()
        .map(|field| format!("{}: {}", field.name, ts_type(&field.ty)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn ts_type(ty: &Type) -> String {
    match ty {
        Type::Bool => "boolean".into(),
        Type::I32 | Type::I64 | Type::U32 | Type::U64 | Type::F64 => "number".into(),
        Type::String => "string".into(),
        Type::Json => "CoreValue".into(),
        Type::Null => "null".into(),
        Type::Named(name) => name.clone(),
        Type::List(inner) => match **inner {
            Type::Optional(_) => format!("({})[]", ts_type(inner)),
            _ => format!("{}[]", ts_type(inner)),
        },
        Type::Optional(inner) => format!("{} | null", ts_type(inner)),
    }
}

fn lower_first(name: &str) -> String {
    let mut chars = name.chars();
    chars
        .next()
        .map(|first| first.to_ascii_lowercase().to_string() + chars.as_str())
        .unwrap_or_default()
}
