//! Generated by reddb-io-toon-rpc-gen from the Calculator IDL (version 1.0). Do not edit.
#![allow(dead_code, non_snake_case, clippy::too_many_arguments)]

use std::sync::Arc;

use reddb_io_toon_rpc::{Client, ClientError, Dispatcher, Params, RpcError, RpcResult};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Vec2 {
    pub x: f64,
    pub y: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Stats {
    pub count: u32,
    pub mean: Option<f64>,
}

/// The Calculator service.
pub trait Calculator: Send + Sync + 'static {
    fn add(&self, a: f64, b: f64) -> RpcResult<f64>;
    fn divide(&self, a: f64, b: f64) -> RpcResult<f64>;
    fn norm(&self, v: Vec2) -> RpcResult<f64>;
    fn stats(&self, values: Vec<f64>) -> RpcResult<Stats>;
    fn echo(&self, text: String) -> RpcResult<String>;
}

/// Register every Calculator method on `dispatcher`, answered by `service`.
pub fn register_calculator(dispatcher: &mut Dispatcher, service: Arc<dyn Calculator>) {
    let service_for_add = service.clone();
    dispatcher.register("add", move |params, _id| {
        #[derive(Deserialize)]
        #[serde(deny_unknown_fields)]
        struct Args {
            a: f64,
            b: f64,
        }
        let args: Args = calculator_params(params, &["a", "b"])?;
        let result = service_for_add.add(args.a, args.b)?;
        serde_json::to_value(result).map_err(|error| RpcError::InternalError(error.to_string()))
    });
    let service_for_divide = service.clone();
    dispatcher.register("divide", move |params, _id| {
        #[derive(Deserialize)]
        #[serde(deny_unknown_fields)]
        struct Args {
            a: f64,
            b: f64,
        }
        let args: Args = calculator_params(params, &["a", "b"])?;
        let result = service_for_divide.divide(args.a, args.b)?;
        serde_json::to_value(result).map_err(|error| RpcError::InternalError(error.to_string()))
    });
    let service_for_norm = service.clone();
    dispatcher.register("norm", move |params, _id| {
        #[derive(Deserialize)]
        #[serde(deny_unknown_fields)]
        struct Args {
            v: Vec2,
        }
        let args: Args = calculator_params(params, &["v"])?;
        let result = service_for_norm.norm(args.v)?;
        serde_json::to_value(result).map_err(|error| RpcError::InternalError(error.to_string()))
    });
    let service_for_stats = service.clone();
    dispatcher.register("stats", move |params, _id| {
        #[derive(Deserialize)]
        #[serde(deny_unknown_fields)]
        struct Args {
            values: Vec<f64>,
        }
        let args: Args = calculator_params(params, &["values"])?;
        let result = service_for_stats.stats(args.values)?;
        serde_json::to_value(result).map_err(|error| RpcError::InternalError(error.to_string()))
    });
    let service_for_echo = service.clone();
    dispatcher.register("echo", move |params, _id| {
        #[derive(Deserialize)]
        #[serde(deny_unknown_fields)]
        struct Args {
            text: String,
        }
        let args: Args = calculator_params(params, &["text"])?;
        let result = service_for_echo.echo(args.text)?;
        serde_json::to_value(result).map_err(|error| RpcError::InternalError(error.to_string()))
    });
}

/// A typed Calculator client over any `Client`.
#[derive(Clone)]
pub struct CalculatorClient {
    client: Client,
}

impl CalculatorClient {
    pub fn new(client: Client) -> Self {
        Self { client }
    }

    pub async fn add(&self, a: f64, b: f64) -> Result<f64, ClientError> {
        let mut params = serde_json::Map::new();
        params.insert("a".into(), serde_json::to_value(a).map_err(|error| ClientError::InvalidCall(error.to_string()))?);
        params.insert("b".into(), serde_json::to_value(b).map_err(|error| ClientError::InvalidCall(error.to_string()))?);
        let result = self.client.call("add", Params::ByName(params)).await?;
        serde_json::from_value(result).map_err(|error| ClientError::Protocol(error.to_string()))
    }

    pub async fn divide(&self, a: f64, b: f64) -> Result<f64, ClientError> {
        let mut params = serde_json::Map::new();
        params.insert("a".into(), serde_json::to_value(a).map_err(|error| ClientError::InvalidCall(error.to_string()))?);
        params.insert("b".into(), serde_json::to_value(b).map_err(|error| ClientError::InvalidCall(error.to_string()))?);
        let result = self.client.call("divide", Params::ByName(params)).await?;
        serde_json::from_value(result).map_err(|error| ClientError::Protocol(error.to_string()))
    }

    pub async fn norm(&self, v: Vec2) -> Result<f64, ClientError> {
        let mut params = serde_json::Map::new();
        params.insert("v".into(), serde_json::to_value(v).map_err(|error| ClientError::InvalidCall(error.to_string()))?);
        let result = self.client.call("norm", Params::ByName(params)).await?;
        serde_json::from_value(result).map_err(|error| ClientError::Protocol(error.to_string()))
    }

    pub async fn stats(&self, values: Vec<f64>) -> Result<Stats, ClientError> {
        let mut params = serde_json::Map::new();
        params.insert("values".into(), serde_json::to_value(values).map_err(|error| ClientError::InvalidCall(error.to_string()))?);
        let result = self.client.call("stats", Params::ByName(params)).await?;
        serde_json::from_value(result).map_err(|error| ClientError::Protocol(error.to_string()))
    }

    pub async fn echo(&self, text: String) -> Result<String, ClientError> {
        let mut params = serde_json::Map::new();
        params.insert("text".into(), serde_json::to_value(text).map_err(|error| ClientError::InvalidCall(error.to_string()))?);
        let result = self.client.call("echo", Params::ByName(params)).await?;
        serde_json::from_value(result).map_err(|error| ClientError::Protocol(error.to_string()))
    }
}

/// Read the params by name (an object) or by position (an array in
/// declaration order).
fn calculator_params<T: serde::de::DeserializeOwned>(
    params: Params,
    names: &[&str],
) -> Result<T, RpcError> {
    let object = match params {
        Params::ByName(object) => object,
        Params::ByPosition(values) if values.len() == names.len() => {
            names.iter().map(|name| name.to_string()).zip(values).collect()
        }
        Params::Absent if names.is_empty() => serde_json::Map::new(),
        _ => {
            return Err(RpcError::InvalidParams(format!(
                "expected {} params",
                names.len()
            )))
        }
    };
    serde_json::from_value(serde_json::Value::Object(object))
        .map_err(|error| RpcError::InvalidParams(error.to_string()))
}
