#!/usr/bin/env node
/**
 * Renders the last `cargo bench` run into a committable Rust baseline.
 *
 * Criterion keeps its baselines under `target/`, which is not committed, so a
 * "compare against the baseline" workflow only works on one machine and only
 * until the next `cargo clean`. This reads criterion's own `estimates.json`
 * files and emits the same markdown shape as the JS harness, so
 * `benchmarks/results/runtime-performance-rust.md` becomes the durable record.
 *
 * Usage:
 *   cargo bench -p reddb-io-toon -- --save-baseline main
 *   node scripts/criterion_baseline_report.mjs [baseline] [outputPath]
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { spawnSync } from 'node:child_process'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const BASELINE = process.argv[2] ?? 'main'
const OUTPUT = process.argv[3] ?? join(REPO_ROOT, 'benchmarks/results/runtime-performance-rust.md')

/**
 * Where criterion actually wrote. The target directory can come from
 * CARGO_TARGET_DIR, a per-project `.cargo/config.toml`, or the user's global
 * one, so `cargo metadata` is asked rather than guessed at.
 */
function criterionDir() {
  const probe = spawnSync('cargo', ['metadata', '--format-version', '1', '--no-deps'], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  })
  const candidates = []
  if (probe.status === 0) {
    candidates.push(join(JSON.parse(probe.stdout).target_directory, 'criterion'))
  }
  if (process.env.CARGO_TARGET_DIR) candidates.push(join(process.env.CARGO_TARGET_DIR, 'criterion'))
  candidates.push(join(REPO_ROOT, 'target/criterion'))
  return candidates.find((path) => existsSync(path))
}

/** Every `<group>/<case>/<baseline>/estimates.json` under the criterion tree. */
function findEstimates(root) {
  const found = []
  const walk = (dir, trail) => {
    for (const entry of readdirSync(dir).sort()) {
      const path = join(dir, entry)
      if (!statSync(path).isDirectory()) continue
      const estimates = join(path, 'estimates.json')
      const benchmark = join(path, 'benchmark.json')
      if (entry === BASELINE && existsSync(estimates) && existsSync(benchmark)) {
        found.push({ estimates, benchmark, trail })
      } else if (entry !== 'report') {
        walk(path, [...trail, entry])
      }
    }
  }
  walk(root, [])
  return found
}

function formatNs(nanos) {
  if (nanos >= 1e9) return `${(nanos / 1e9).toFixed(2)} s`
  if (nanos >= 1e6) return `${(nanos / 1e6).toFixed(2)} ms`
  if (nanos >= 1e3) return `${(nanos / 1e3).toFixed(2)} µs`
  return `${nanos.toFixed(0)} ns`
}

const root = criterionDir()
if (!root) {
  console.error('No criterion output found. Run:\n  cargo bench -p reddb-io-toon -- --save-baseline main')
  process.exit(1)
}

const rows = findEstimates(root).map(({ estimates, benchmark }) => {
  const estimate = JSON.parse(readFileSync(estimates, 'utf8'))
  const meta = JSON.parse(readFileSync(benchmark, 'utf8'))
  const medianNs = estimate.median.point_estimate
  const bytes = meta.throughput?.Bytes ?? null
  return {
    group: meta.group_id,
    name: meta.function_id ?? meta.value_str ?? meta.benchmark_id,
    medianNs,
    bytes,
    mibPerSecond: bytes ? bytes / 1024 / 1024 / (medianNs / 1e9) : null,
  }
})

if (rows.length === 0) {
  console.error(`No '${BASELINE}' baseline found under ${root}.\nRun: cargo bench -p reddb-io-toon -- --save-baseline ${BASELINE}`)
  process.exit(1)
}

const lines = [
  '# Runtime performance — Rust (`reddb-io-toon`)',
  '',
  'Generated by `scripts/criterion_baseline_report.mjs` from the criterion',
  `\`${BASELINE}\` baseline. To refresh:`,
  '',
  '```bash',
  'cargo bench -p reddb-io-toon -- --save-baseline main',
  'node scripts/criterion_baseline_report.mjs',
  '```',
  '',
  'Wall-clock medians on the machine that produced this file. Compare against a',
  're-run on *your* machine, never against a number from another one; see',
  '`benchmarks/README.md` for how to read this.',
  '',
]

for (const group of [...new Set(rows.map((row) => row.group))]) {
  lines.push(`## ${group}`, '', '| Dataset | Input bytes | Median | MiB/s |', '| --- | ---: | ---: | ---: |')
  for (const row of rows.filter((candidate) => candidate.group === group)) {
    lines.push(
      `| \`${row.name}\` | ${row.bytes ?? 'n/a'} | ${formatNs(row.medianNs)} | ` +
        `${row.mibPerSecond ? row.mibPerSecond.toFixed(1) : 'n/a'} |`,
    )
  }
  lines.push('')
}

mkdirSync(dirname(OUTPUT), { recursive: true })
writeFileSync(OUTPUT, `${lines.join('\n')}\n`)
console.log(`Wrote ${relative(REPO_ROOT, OUTPUT)} (${rows.length} benchmarks)`)
