import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..')
const read = (path) => readFileSync(resolve(root, path), 'utf8')

const currentSurfaces = [
  'README.md',
  'packages/toon/README.md',
  'packages/toon/package.json',
  'crates/toon/README.md',
  'crates/toon/Cargo.toml',
  'crates/tq/README.md',
  'crates/tq/Cargo.toml',
  'packages/vscode-toon/README.md',
  'packages/vscode-toon/package.json',
  'packages/vscode-toon/syntaxes/toon.tmLanguage.json',
  'packages/vscode-toon/syntaxes/toonl.tmLanguage.json',
  'benchmarks/README.md',
  'docs/toon-official-spec.md',
  'docs/toon-reddb-spec.md',
  'docs/toonl-reddb-spec.md',
  'docs/proposals/README.md',
  'docs/proposals/nested-tabular-headers.md',
  'docs/proposals/keyed-map-collapse.md',
  'docs/proposals/discriminated-heterogeneous-arrays.md',
]

test('current user-facing surfaces describe the v4.1 baseline without retired claims', () => {
  for (const path of currentSurfaces) {
    const source = read(path)
    assert.doesNotMatch(source, /v3\.3/i, `${path} must not present the retired baseline`)
    assert.doesNotMatch(source, /no build step/i, `${path} must not deny the published build`)
    assert.doesNotMatch(source, /compatibility aliases/i, `${path} must not call no-op flags aliases`)
    assert.doesNotMatch(source, /100% conformance/i, `${path} must not make an unscoped parity claim`)
  }
})

test('known upstream issue mappings cannot regress', () => {
  assert.doesNotMatch(read('docs/proposals/delimiter-choice.md'), /(?:spec#|issues\/|pull\/)48/i)
  assert.doesNotMatch(read('docs/proposals/primitive-array-columns.md'), /(?:spec#|issues\/|pull\/)49/i)

  const feedback = read('docs/upstream-feedback.md')
  assert.match(feedback, /spec#48[^\n]*mixed columnar arrays/i)
  assert.match(feedback, /spec#49[^\n]*(?:roadmap|tabular-generalization)/i)
})

test('frontier status is dated and separates every authority state', () => {
  const official = read('docs/toon-official-spec.md')
  assert.match(official, /audited (?:on|at) 2026-08-07/i)
  for (const status of ['released', 'merged', 'draft', 'conflicting', 'rejected', 'userland-only']) {
    assert.match(official, new RegExp(`\\b${status}\\b`, 'i'), `missing ${status} status`)
  }
})

test('migration notes show observable TypeScript and Rust cutovers', () => {
  const migration = read('docs/migration-v4.md')
  assert.match(migration, /TypeScript cutover/i)
  assert.match(migration, /Rust cutover/i)
  assert.match(migration, /@reddb-io\/toon\/legacy/)
  assert.match(migration, /parse_legacy/)
  assert.match(migration, /Before[^\n]*After/is)
})

test('benchmark claims point to their public-path reproduction commands', () => {
  const benchmarkIndex = read('benchmarks/README.md')
  for (const command of [
    'pnpm benchmark:accuracy:verify',
    'pnpm benchmark:tokens',
    'pnpm benchmark:performance',
    'cargo bench -p reddb-io-toon',
  ]) {
    assert.match(benchmarkIndex, new RegExp(command.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
  }

  for (const path of [
    'benchmarks/results/2026-07-15-retrieval-accuracy.md',
    'benchmarks/results/2026-08-06-token-efficiency.md',
    'benchmarks/results/runtime-performance-js.md',
    'benchmarks/results/runtime-performance-rust.md',
  ]) {
    assert.match(read(path), /(?:Command|Generated by|cargo bench)/i, `${path} needs reproduction evidence`)
  }
})

test('relative Markdown links in user-facing docs resolve in a clean checkout', () => {
  const markdownFiles = currentSurfaces.filter((path) => path.endsWith('.md')).concat([
    'CHANGELOG.md',
    'docs/migration-v4.md',
    'docs/upstream-feedback.md',
    'docs/upstream-monitoring.md',
    'docs/proposals/primitive-array-columns.md',
    'docs/proposals/child-tables-and-matrix.md',
    'docs/proposals/depth-guard.md',
    'docs/proposals/delimiter-choice.md',
    'docs/proposals/detect-truncation.md',
    'docs/proposals/cyclic-discriminated-arrays.md',
  ])

  for (const path of markdownFiles) {
    const source = read(path)
    for (const match of source.matchAll(/!?(?:\[[^\]]*\])\(([^)]+)\)/g)) {
      const target = match[1].split('#', 1)[0]
      if (!target || /^(?:https?:|mailto:)/.test(target)) continue
      const resolved = resolve(root, dirname(path), decodeURIComponent(target))
      assert.ok(existsSync(resolved), `${path} links to missing ${target}`)
    }
  }
})
